GET /it_IT/parrocchetto.jpg HTTP/1.1
Accept:         */*
Connection:     keep-alive
Host:           127.0.0.1:8087
If-Range:       Sun, 15 Apr 2018 22:59:53 GMT
Range:          bytes=135168-
User-Agent:     WebDAVFS/3.0.0 (03008000) Darwin/17.4.0 (x86_64)
X-Php-Ob-Level: 1

