HTTP/1.0 207 Multi-Status
Cache-Control: no-cache, private
Content-Type:  application/xml; charset="utf-8"
Date:          Fri, 20 Apr 2018 00:36:01 GMT

<?xml version="1.0" encoding="utf-8"?>
<D:multistatus xmlns:D="DAV:">
        <D:response>
        <D:href>/</D:href>
        <D:propstat>
            <D:status>HTTP/1.1 200 OK</D:status>
            <D:prop>
                <D:creationdate>2018-04-20T02:35:43+02:00</D:creationdate>
                <D:getcontentlength>0</D:getcontentlength>
                <D:getlastmodified>Fri, 20 Apr 2018 02:35:43 +0200</D:getlastmodified>
                <D:resourcetype><D:collection/></D:resourcetype>
            </D:prop>
        </D:propstat>
    </D:response>

        <D:response>
        <D:href>/birds</D:href>
        <D:propstat>
            <D:status>HTTP/1.1 200 OK</D:status>
            <D:prop>
                <D:creationdate>2018-04-20T02:36:01+02:00</D:creationdate>
                <D:getcontentlength>0</D:getcontentlength>
                <D:getlastmodified>Fri, 20 Apr 2018 02:36:01 +0200</D:getlastmodified>
                <D:resourcetype><D:collection/></D:resourcetype>
            </D:prop>
        </D:propstat>
    </D:response>
        <D:response>
        <D:href>/example.json</D:href>
        <D:propstat>
            <D:status>HTTP/1.1 200 OK</D:status>
            <D:prop>
                <D:creationdate>2018-04-20T00:37:52+02:00</D:creationdate>
                <D:getcontentlength>19</D:getcontentlength>
                <D:getlastmodified>Fri, 20 Apr 2018 00:37:52 +0200</D:getlastmodified>
                <D:resourcetype>text/plain</D:resourcetype>
            </D:prop>
        </D:propstat>
    </D:response>
        <D:response>
        <D:href>/hello.txt</D:href>
        <D:propstat>
            <D:status>HTTP/1.1 200 OK</D:status>
            <D:prop>
                <D:creationdate>2018-04-20T00:37:52+02:00</D:creationdate>
                <D:getcontentlength>13</D:getcontentlength>
                <D:getlastmodified>Fri, 20 Apr 2018 00:37:52 +0200</D:getlastmodified>
                <D:resourcetype>text/plain</D:resourcetype>
            </D:prop>
        </D:propstat>
    </D:response>
        <D:response>
        <D:href>/it_IT</D:href>
        <D:propstat>
            <D:status>HTTP/1.1 200 OK</D:status>
            <D:prop>
                <D:creationdate>2018-04-20T00:37:52+02:00</D:creationdate>
                <D:getcontentlength>0</D:getcontentlength>
                <D:getlastmodified>Fri, 20 Apr 2018 00:37:52 +0200</D:getlastmodified>
                <D:resourcetype><D:collection/></D:resourcetype>
            </D:prop>
        </D:propstat>
    </D:response>
        <D:response>
        <D:href>/test.txt</D:href>
        <D:propstat>
            <D:status>HTTP/1.1 200 OK</D:status>
            <D:prop>
                <D:creationdate>2018-04-20T00:52:19+02:00</D:creationdate>
                <D:getcontentlength>58</D:getcontentlength>
                <D:getlastmodified>Fri, 20 Apr 2018 00:52:19 +0200</D:getlastmodified>
                <D:resourcetype>text/plain</D:resourcetype>
            </D:prop>
        </D:propstat>
    </D:response>
        <D:responsedescription> OK.</D:responsedescription>
</D:multistatus>
