LOCK /birds/.DS_Store HTTP/1.1
Accept:         */*
Connection:     keep-alive
Content-Length: 229
Content-Type:   text/xml; charset="utf-8"
Cookie:         sf_redirect=deleted
Depth:          0
Host:           127.0.0.1:8000
Timeout:        Second-600
User-Agent:     WebDAVFS/3.0.0 (03008000) Darwin/17.5.0 (x86_64)
X-Php-Ob-Level: 1
Cookie: sf_redirect=deleted

<?xml version="1.0" encoding="utf-8"?>
<D:lockinfo xmlns:D="DAV:">
<D:lockscope><D:exclusive/></D:lockscope>
<D:locktype><D:write/></D:locktype>
<D:owner>
<D:href>http://www.apple.com/webdav_fs/</D:href>
</D:owner>
</D:lockinfo>
