HTTP/1.0 404 Not Found
Cache-Control: no-cache, private
Date:          Fri, 20 Apr 2018 00:34:51 GMT

/Users/adam/Sites/airship/var/files/.metadata_never_index does not exist. dir /Users/adam/Sites/airship/var/files