HTTP/1.0 404 Not Found
Cache-Control: no-cache, private
Date:          Fri, 20 Apr 2018 00:35:50 GMT

/Users/adam/Sites/airship/var/files/._birds does not exist. dir /Users/adam/Sites/airship/var/files