HTTP/1.0 404 Not Found
Cache-Control: no-cache, private
Date:          Fri, 20 Apr 2018 00:36:01 GMT

/Users/adam/Sites/airship/var/files/birds/bald eagle.jpg does not exist. dir /Users/adam/Sites/airship/var/files