HTTP/1.0 200 OK
Cache-Control: no-cache, private
Content-Type:  application/xml; charset="utf-8"
Date:          Fri, 20 Apr 2018 00:35:30 GMT
Lock-Token:    <urn:uuid:d68e38a5-ca60-4011-affa-31d8492c7c7d>

<?xml version="1.0" encoding="utf-8"?>
<D:prop xmlns:D="DAV:">
    <D:lockdiscovery>
        <D:activelock>
            <D:locktype><D:write/></D:locktype>
            <D:lockscope><D:exclusive/></D:lockscope>
            <D:depth>0</D:depth>
                                                    <D:timeout>Second-300</D:timeout>
            <D:locktoken>
                <D:href>urn:uuid:d68e38a5-ca60-4011-affa-31d8492c7c7d</D:href>
            </D:locktoken>
            <D:lockroot>
                <D:href>http://127.0.0.1:8000/birds/%D0%B3%D0%BE%D0%BB%D1%83%D0%B1%D0%BA%D0%B0.jpeg</D:href>
            </D:lockroot>
        </D:activelock>
    </D:lockdiscovery>
</D:prop>
