# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false
        bind:
            $projectDir: '%kernel.project_dir%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/App/*'
        exclude: '../src/App/{Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/App/Controller'
        tags: ['controller.service_arguments']

    Ramsey\Uuid\UuidFactory:
        class: Ramsey\Uuid\UuidFactory

    Airship\Webdav\Lock\LockTender:
        class: Airship\Webdav\Lock\LockTender
        arguments:
            - '@lock.factory'
            - '@Ramsey\Uuid\UuidFactory'
            - '@cache.locktender'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
